version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - /home/universidad/mysql/:/var/lib/mysql